import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ElectionCard } from "@/components/election-card";
import { EditorialImage } from "@/components/editorial-media";
import { Button } from "@/components/ui/button";
import { forState, stateNames, states } from "@/lib/data";
export const dynamicParams=false;
export function generateStaticParams(){return states.map(([state])=>({state:state.toLowerCase()}));}
export async function generateMetadata({params}:{params:Promise<{state:string}>}):Promise<Metadata>{const raw=await params;const name=stateNames[raw.state.toUpperCase()];return {title:name?`${name} election calendar`:"State election calendar",description:name?`Verified 2026 election dates, voter deadlines, and official sources for ${name}.`:"Verified 2026 election dates and voter deadlines."};}
export default async function StatePage({params}:{params:Promise<{state:string}>}){const raw=await params;const state=raw.state.toUpperCase();const items=forState(state);const name=stateNames[state];if(!name)notFound();return <div className="mx-auto max-w-7xl px-5 py-14 lg:px-8"><nav className="rule-label"><Link href="/states/">States</Link> / {state}</nav><div className="mt-8 grid gap-8 border-b pb-10 md:grid-cols-[1fr_auto] md:items-end"><div><p className="rule-label">State desk / {state}</p><h1 className="mt-2 font-serif text-5xl font-bold">{name}</h1><p className="mt-4 text-lg text-muted-foreground">{items.length} reviewed election {items.length===1?"record":"records"} in the current edition.</p></div><Button asChild variant="outline"><a href={items[0]?.source_url} target="_blank" rel="noreferrer">Visit election authority</a></Button></div><EditorialImage className="mt-10" src="/images/election/constituent-listening.png" alt="A community leader listens to constituents gathered in a civic hall." eyebrow="The state desk" caption={`Election calendars begin with people: voters, officials, and communities preparing for the next ${name} contest.`} frameClassName="aspect-[16/7]" imageClassName="object-[center_42%]" sizes="(min-width: 1280px) 80rem, 100vw" />{items.length?<div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map((e,i)=><ElectionCard key={e.id} election={e} featured={i===0}/>)}</div>:<div className="mt-10 border bg-card p-8"><h2 className="font-serif text-2xl font-bold">No verified dates yet</h2><p className="mt-2 text-muted-foreground">We publish only after a source can support the record.</p></div>}</div>}
