import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowUpRight, Clock3, Landmark, Scale } from "lucide-react";
import { ConfidenceBadge, DeadlineList } from "@/components/election-card";
import { EditorialImage } from "@/components/editorial-media";
import { Button } from "@/components/ui/button";
import { elections, findElection, formatDate, stateHref, titleCase } from "@/lib/data";
export const dynamicParams=false;
export function generateStaticParams(){return elections.map(e=>({state:e.state,slug:e.slug,id:e.id}));}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const e=findElection(id);return e?{title:`${e.jurisdiction_name} ${titleCase(e.election_type)} Election`,description:`${formatDate(e.election_date)} — offices, voter deadlines, and official source for ${e.jurisdiction_name}.`}:{title:"Election not found"};}
export default async function ElectionPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const e=findElection(id);if(!e)notFound();return <article className="mx-auto max-w-6xl px-5 py-14 lg:px-8"><nav className="rule-label"><Link href="/states/">States</Link> / <Link href={stateHref(e.state)}>{e.state}</Link> / Election brief</nav><header className="mt-8 grid gap-10 border-b pb-12 md:grid-cols-[1fr_18rem]"><div><div className="flex flex-wrap items-center gap-3"><ConfidenceBadge confidence={e.confidence}/><span className="rule-label">{titleCase(e.election_type)} election</span></div><h1 className="mt-5 text-balance font-serif text-5xl font-bold">{e.jurisdiction_name}</h1><p className="mt-5 font-serif text-3xl text-secondary">{formatDate(e.election_date)}</p><p className="mt-4 max-w-2xl text-muted-foreground">{e.notes}</p></div><div className="flex flex-col justify-center border-l border-secondary pl-7"><span className="rule-label">Election date</span><strong className="mt-2 font-serif text-7xl leading-none text-secondary">{new Date(`${e.election_date}T12:00:00`).getDate()}</strong><span className="mt-1 font-mono text-sm">{new Date(`${e.election_date}T12:00:00`).toLocaleDateString("en",{month:"long",year:"numeric"})}</span></div></header><EditorialImage className="mt-10" src="/images/election/ballot-box.png" alt="A voter places a paper ballot into a secured ballot box at a polling place." eyebrow="At the polls" caption="The dates below structure the journey to this moment—from registration and early voting through election day." frameClassName="aspect-[16/7]" imageClassName="object-[center_53%]" sizes="(min-width: 1152px) 72rem, 100vw" /><div className="mt-12 grid gap-12 md:grid-cols-[1.1fr_.9fr]"><section><p className="rule-label">Voter calendar</p><h2 className="mt-2 font-serif text-3xl font-bold">Deadlines and windows</h2><div className="mt-6"><DeadlineList election={e}/></div></section><section><p className="rule-label">Ballot scope</p><h2 className="mt-2 font-serif text-3xl font-bold">Offices tracked</h2><ul className="mt-6 border-t">{e.offices.map(o=><li key={o} className="flex gap-3 border-b py-4"><Landmark className="size-5 text-secondary" aria-hidden="true"/><span>{o}</span></li>)}</ul></section></div><section className="mt-14 border bg-card p-7"><div className="grid gap-7 md:grid-cols-[1fr_auto]"><div><p className="rule-label">Source and provenance</p><h2 className="mt-2 font-serif text-2xl font-bold">Trace this record to the source.</h2><div className="mt-5 flex flex-col gap-3 text-sm text-muted-foreground"><p className="flex gap-2"><Scale className="size-4"/>Confidence: {e.confidence}</p>{e.source_retrieved_at&&<p className="flex gap-2"><Clock3 className="size-4"/>Retrieved {new Date(e.source_retrieved_at).toLocaleDateString()}</p>}</div></div><Button asChild><a href={e.source_url} target="_blank" rel="noreferrer">Open official source <ArrowUpRight data-icon="inline-end"/></a></Button></div></section></article>}
